services:
  nebula-sync:
    image: ghcr.io/lovelaze/nebula-sync:latest # latest is stable
    container_name: nebula-sync
    environment:
    - PRIMARY=http://{{ hostvars['rpi1'].ansible_host }}|{{ primary_pihole_admin_password }}
    - REPLICAS=http://{{ hostvars['rpi2'].ansible_host }}|{{ secondary_pihole_admin_password }}
    - FULL_SYNC=true
    - RUN_GRAVITY=true
    - CRON=0 * * * *