services:
  unifi-db:
    image: docker.io/mongo:4.4
    container_name: unifi-db
    networks:
      - proxy
    volumes:
      - "{{ docker_appdata_directory }}/unifi/data:/data/db"
      - "{{ docker_appdata_directory }}/unifi/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro"
    restart: unless-stopped
  
  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    depends_on:
      - unifi-db
    environment:
      - PUID=1000
      - PGID=1000
      - TZ={{ timezone }}
      - MONGO_USER=unifi
      - MONGO_PASS=5nHgg3G0cH9d
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
      - MEM_LIMIT=1024 #optional
      - MEM_STARTUP=1024 #optional
    volumes:
      - "{{ docker_appdata_directory }}/unifi/config:/config"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.unifi-network-application.rule=Host(`unifi.{{ local_domain }}`)"
      - "traefik.http.routers.unifi-network-application.entrypoints=https"
      - "traefik.http.routers.unifi-network-application.middlewares=unifiHeaders@file"
      - "traefik.http.services.unifi-network-application.loadbalancer.server.port=8443"
      - "traefik.http.services.unifi-network-application.loadbalancer.server.scheme=https"
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8083:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped

networks:
  proxy:
    external: true