username: tompo
domain: hotdamndog.com
local_domain: "local.{{ domain }}"
timezone: America/Los_Angeles
email: "{{ vault_email }}"
nas_ip_address: "192.168.0.108" #move to secrets
packages:
  - vim
  - neofetch 
  - htop

# Docker settings
docker_directory: /opt/docker
docker_appdata_directory: /opt/docker/appdata
docker_compose_directory: /opt/docker/compose