- name: Update system packages
  apt:
    update_cache: yes
    upgrade: yes
    autoremove: yes
    cache_valid_time: 3600

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    reboot_timeout: 300 #todo: check if this is needed
    connect_timeout: 30 #todo: check if this is needed
    msg: "Reboot initiated by Ansible for package updates"
  when: reboot_required_file.stat.exists == true

- name: Install default packages
  package:
    name: "{{ packages }}"
    state: present

- name: Adds entry for {{ inventory_hostname }} in /etc/hosts
  ansible.builtin.lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ inventory_hostname }}"
    owner: root
    group: root
    mode: '0644'
