- name: Set the name of a sudo group
  set_fact:
    sudo_group: sudo

- name: Ensure the necessary groups exist
  group:
    name: "{{ item }}"
    state: present
  loop:
      - "{{ username }}"
      - docker
   
- name: Create a login user
  user:
    name: "{{ username }}"
    password: "{{ password | password_hash('sha512') }}"
    groups: 
      - "{{ sudo_group }}"
      - docker
      - users
    state: present
    append: true

- name: Adjust permissions on home directory
  file:
    path: "/home/{{ username }}"
    state: directory
    mode: 0755
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Passwordless sudo for {{ username }}
  lineinfile:
    path: /etc/sudoers
    regexp: "^%wheel"
    line: '{{ username }} ALL=(ALL) NOPASSWD:ALL'
    state: present
    validate: 'visudo -cf %s'

- name:  Disable ssh password authentication
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: 'PasswordAuthentication no'
    state: present
    backup: yes
  notify:
    - Restart SSH