server:
  host: 0.0.0.0
  port: 9091
log:
  level: debug
theme: dark
# This secret can also be set using the env variables AUTHELIA_JWT_SECRET_FILE
jwt_secret: "{{ authelia_jwt_secret }}"
default_redirection_url: "https://auth.{{ local_domain }}"
totp:
  issuer: "{{ local_domain }}"

# duo_api:
#  hostname: api-123456789.example.com
#  integration_key: ABCDEF
#  # This secret can also be set using the env variables AUTHELIA_DUO_API_SECRET_KEY_FILE
#  secret_key: 1234567890abcdefghifjkl

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      salt_length: 16
      parallelism: 8
      memory: 64
      
access_control:
  default_policy: deny
  rules:
    - domain: "pihole.{{ local_domain }}"
      policy: bypass
    - domain: "prox.{{ local_domain }}"
      policy: bypass
    - domain: "auth.{{ local_domain }}"
      policy: bypass
    - domain: "books.{{ local_domain }}"
      policy: one_factor
    - domain: "traefik.{{ local_domain }}"
      policy: one_factor
    - domain: "jellyfin.{{ local_domain }}"
      policy: bypass
    - domain: "nextcloud.{{ local_domain }}"
      policy: bypass
    - domain: "radarr.{{ local_domain }}"
      policy: bypass
    - domain: "sonarr.{{ local_domain }}"
      policy: bypass
    - domain: "paperless.{{ local_domain }}"
      policy: bypass
    - domain: "qbit.{{ local_domain }}"
      policy: bypass
    - domain: "prowlarr.{{ local_domain }}"
      policy: bypass
    - domain: "sabnzbd.{{ local_domain }}"
      policy: bypass
    - domain: "homeassistant.{{ local_domain }}"
      policy: bypass
    - domain: "sonarqube.{{ local_domain }}"
      policy: bypass
    - domain: "bookstack.{{ local_domain }}"
      policy: bypass
    - domain: "navidrome.{{ local_domain }}"
      policy: bypass
    - domain: "immich.{{ local_domain }}"
      policy: bypass
    - domain: "unifi.{{ local_domain }}"
      policy: bypass
    - domain: "tandoor.{{ local_domain }}"
      policy: bypass

session:
  name: authelia_session
  secret: "{{ authelia_session_secret }}"
  expiration: 3600  # 1 hour
  inactivity: 300  # 5 minutes
  domain: "{{ local_domain }}" #Should match whatever your root protected domain is

  # redis:
  #   host: redis
  #   port: 6379
  #   # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD_FILE
  #   # password: authelia

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: "{{authelia_sqlite_encryption_key}}"
  local:
    path: /config/db.sqlite3

notifier:
  # smtp:
  #   username: test
  #   # This secret can also be set using the env variables AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE
  #   password: password
  #   host: mail.example.com
  #   port: 25
  #   sender: admin@example.com
  filesystem:
    filename: /config/notification.txt