- name: Verify that authelia directories exists
  file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_directory }}/authelia"
    - "{{ docker_appdata_directory }}/authelia"

- name: Copy authelia compose.yml
  template:
    src: ./roles/containers/authelia/compose.yml
    dest: "{{ docker_compose_directory }}/authelia/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Copy authelia configuration.yml
  template:
    src: ./roles/containers/authelia/configuration.yml
    dest: "{{ docker_appdata_directory }}/authelia/configuration.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Copy authelia users_database.yml
  template:
    src: ./roles/containers/authelia/users_database.yml
    dest: "{{ docker_appdata_directory }}/authelia/users_database.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up authelia container
  community.docker.docker_compose:
    project_src: "{{ docker_compose_directory }}/authelia/"