- name: Verify that bookstack directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_directory }}/bookstack"

- name: Copy bookstack compose.yml
  template:
    src: ./roles/containers/bookstack/compose.yml
    dest: "{{ docker_compose_directory }}/bookstack/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up bookstack container
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_directory }}/bookstack/"