- name: Verify that gluetun directories exists
  ansible.builtin.file:
    path: "{{ gluetun_directory }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Copy gluetun docker-compose.yml
  template:
    src: ./roles/containers/gluetun/compose.yml
    dest: "{{ gluetun_directory }}/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up gluetun container
  community.docker.docker_compose:
    project_src: "{{ gluetun_directory }}"