- name: Verify that gluetun directories exists
  ansible.builtin.file:
    path: "{{ docker_compose_directory }}/gluetun"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Copy gluetun compose.yml
  template:
    src: ./roles/containers/gluetun/compose.yml
    dest: "{{ docker_compose_directory }}/gluetun/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up gluetun container
  community.docker.docker_compose:
    project_src: "{{ docker_compose_directory }}/gluetun/"