- name: Verify that home assistant directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ home_assistant_directory }}"
    - "{{ docker_compose_directory }}/home_assistant"

- name: Copy home assistant docker-compose.yml
  template:
    src: ./roles/containers/home_assistant/compose.yml
    dest: "{{ home_assistant_directory }}/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up home assistant container
  community.docker.docker_compose_v2:
    project_src: "{{ home_assistant_directory }}"