- name: Verify that jellyfin directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_directory }}/jellyfin"
    - "{{ docker_appdata_directory }}/jellyfin"
    - "{{ docker_appdata_directory }}/jellyfin/config"
    - "{{ docker_appdata_directory }}/jellyfin/cache"

- name: Copy jellyfin docker-compose.yml
  template:
    src: ./roles/containers/jellyfin/compose.yml
    dest: "{{ docker_compose_directory }}/jellyfin/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up jellyfin container
  community.docker.docker_compose:
    project_src: "{{ docker_compose_directory }}/jellyfin/"