- name: Verify that nextcloud directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_directory }}/nextcloud"

- name: Copy nextcloud docker-compose.yml
  template:
    src: ./roles/containers/nextcloud/compose.yml
    dest: "{{ docker_compose_directory }}/nextcloud/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up nextcloud container
  community.docker.docker_compose:
    project_src: "{{ docker_compose_directory }}/nextcloud"