- name: Verify that openbooks directory exists
  file:
    path: "{{ openbooks_directory }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory

- name: Copy openbooks docker-compose.yml
  template:
    src: ./roles/containers/openbooks/compose.yml
    dest: "{{ openbooks_directory }}/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up openbooks container
  community.docker.docker_compose:
    project_src: "{{ openbooks_directory }}"