- name: Verify that orbital sync directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_directory }}/orbital_sync"

- name: Copy orbital_sync compose.yml
  template:
    src: ./roles/containers/orbital_sync/compose.yml
    dest: "{{ docker_compose_directory }}/orbital_sync/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up orbital sync container
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_directory }}/orbital_sync/"