- name: Verify that radarr directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ radarr_directory }}"
    - "{{ radarr_directory }}/config"
    - "{{ radarr_directory }}/data"

- name: Copy radarr docker-compose.yml
  template:
    src: ./roles/containers/radarr/compose.yml
    dest: "{{ radarr_directory }}/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up radarr container
  community.docker.docker_compose:
    project_src: "{{ radarr_directory }}"