- name: Verify that traefik directories exists
  file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
  loop:
    - "{{ docker_compose_directory }}/traefik"
    - "{{ docker_appdata_directory }}/traefik"

- name: Copy traefik docker-compose.yml
  template:
    src: ./roles/containers/traefik/compose.yml
    dest: "{{ docker_compose_directory }}/traefik/compose.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Ensures acme.json file exists
  file:
    path: "{{ docker_appdata_directory }}/traefik/acme.json"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"
    mode: "0600"

- name: Adding traefik.yml file
  template:
    src: ./roles/containers/traefik/traefik.yml
    dest: "{{ docker_appdata_directory }}/traefik/traefik.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Adding traefik config file
  template:
    src: ./roles/containers/traefik/config.yml
    dest: "{{ docker_appdata_directory }}/traefik/config.yml"
    owner: "{{ username }}"
    group: "{{ username }}"
    force: yes

- name: Docker-compose up traefik container
  community.docker.docker_compose_v2:
    project_src: "{{ docker_compose_directory }}/traefik"