http:
  routers:
    pihole:
      entryPoints:
        - "https"
      rule: "Host(`pihole.{{ local_domain }}`)"
      middlewares:
        - redirectregex-pihole
        - addprefix-pihole
      tls: {}
      service: pihole
    proxmox:
      rule: "Host(`pve.{{ local_domain }}`)"
      entryPoints:
        - "https"
      service: proxmox
      tls: {}

  services:
    pihole:
      loadBalancer:
        servers:
          - url: "http://{{ hostvars['rpi1'].ansible_host }}:80"
    proxmox:
      loadBalancer:
        servers:
          - url: "http://10.0.0.5:8006"

  middlewares:
    authelia:
      forwardAuth:
        address: "http://authelia:9091/api/verify?rd=https://auth.{{ local_domain }}"
        trustForwardHeader: true
        authResponseHeaders:
          - Remote-User
          - Remote-Groups
          - Remote-Name
          - Remote-Email
    default-allowlist:
      ipAllowList:
        sourceRange:
          - "10.0.0.0/8"
          - "192.168.0.0/16"
          - "172.16.0.0/12"
    securityHeaders:
      headers:
        customResponseHeaders:
          X-Robots-Tag: "none,noarchive,nosnippet,notranslate,noimageindex"
          X-Forwarded-Proto: "https"
          server: ""
        sslProxyHeaders:
          X-Forwarded-Proto: https
        referrerPolicy: "same-origin"
        hostsProxyHeaders:
          - "X-Forwarded-Host"
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        contentTypeNosniff: true
        forceSTSHeader: true
        stsIncludeSubdomains: true
        stsSeconds: 63072000
        stsPreload: true
    unifiHeaders:
      headers:
        customRequestHeaders:
          Authorization: "" # Removes
    addprefix-pihole:
      addPrefix:
        prefix: "/admin"
    redirectregex-pihole:
      redirectRegex:
        regex: /admin/$
        replacement: /
